# Generated by Django 5.0.6 on 2024-09-05 13:31

import FitSite.models
import FitSite.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to=FitSite.models.user_directory_path, validators=[FitSite.validators.validate_image_size], verbose_name='Изображение'),
        ),
    ]
